//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessPlatform
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FitnessEntities : DbContext
    {
        public FitnessEntities()
            : base("name=FitnessEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tActivity> tActivity { get; set; }
        public virtual DbSet<tAdmin> tAdmin { get; set; }
        public virtual DbSet<tCoach> tCoach { get; set; }
        public virtual DbSet<tCoachRest> tCoachRest { get; set; }
        public virtual DbSet<tLesson> tLesson { get; set; }
        public virtual DbSet<tLessonAbout> tLessonAbout { get; set; }
        public virtual DbSet<tMember> tMember { get; set; }
        public virtual DbSet<tOrder> tOrder { get; set; }
        public virtual DbSet<tRecord> tRecord { get; set; }
        public virtual DbSet<tStudio> tStudio { get; set; }
        public virtual DbSet<tTime> tTime { get; set; }
        public virtual DbSet<tClass> tClass { get; set; }
        public virtual DbSet<tContacts> tContacts { get; set; }
        public virtual DbSet<tFoodList> tFoodList { get; set; }
    }
}
