//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessPlatform
{
    using System;
    using System.Collections.Generic;
    
    public partial class tAdmin
    {
        public int fId { get; set; }
        public string fAdminIdName { get; set; }
        public string fAdminGender { get; set; }
        public Nullable<int> fAdminAge { get; set; }
        public string fAdminCID { get; set; }
        public Nullable<System.DateTime> fAdminBirthday { get; set; }
        public string fAdminPhone { get; set; }
        public string fAdminAddress { get; set; }
        public string fAdminEmail { get; set; }
        public string fAdminPassword { get; set; }
        public Nullable<System.DateTime> fAdminTime { get; set; }
        public int fAdminId { get; set; }
    }
}
