//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessPlatform
{
    using System;
    using System.Collections.Generic;
    
    public partial class tClass
    {
        public string TrainingId { get; set; }
        public string TrainingName { get; set; }
        public string TrainingCount { get; set; }
        public string TrainingWeight { get; set; }
        public string TrainingRest { get; set; }
        public Nullable<int> fMemberId { get; set; }
        public Nullable<int> fCoachId { get; set; }
        public Nullable<System.DateTime> fTrainingDate { get; set; }
    }
}
