//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessPlatform
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCoach
    {
        public int fCoachID { get; set; }
        public string fCoachName { get; set; }
        public string fCoachGender { get; set; }
        public Nullable<System.DateTime> fCoachBirthday { get; set; }
        public string fCoachGID { get; set; }
        public string fCoachPhone { get; set; }
        public string fCoachAddress { get; set; }
        public string fCoachMail { get; set; }
        public string fCoachPassword { get; set; }
        public string fCoachimg { get; set; }
        public string fCoachLicense { get; set; }
        public Nullable<int> fCoachSuccess { get; set; }
    }
}
