//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessPlatform
{
    using System;
    using System.Collections.Generic;
    
    public partial class tLesson
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tLesson()
        {
            this.tLessonAbout = new HashSet<tLessonAbout>();
        }
    
        public int fLessonId { get; set; }
        public string fLessonName { get; set; }
        public string fLessontime { get; set; }
        public string fLessonRest { get; set; }
        public Nullable<decimal> fLessonWeight { get; set; }
    
        public virtual tLesson tLesson1 { get; set; }
        public virtual tLesson tLesson2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tLessonAbout> tLessonAbout { get; set; }
    }
}
