//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessPlatform
{
    using System;
    using System.Collections.Generic;
    
    public partial class tOrder
    {
        public int fid { get; set; }
        public int forderid { get; set; }
        public int fMemberId { get; set; }
        public int fCoachID { get; set; }
        public int fLessonId { get; set; }
        public int fSuccessed { get; set; }
        public int fGynId { get; set; }
        public System.DateTime fStartTime { get; set; }
        public System.DateTime fEndTime { get; set; }
        public string fTrainingName { get; set; }
        public System.DateTime fApplyTime { get; set; }
        public Nullable<int> fOrderlike { get; set; }
        public string fOrderAbout { get; set; }
    }
}
